### ISSUE TITLE
Can it be built without the youtube API key?

### ISSUE THREAD

**Issue by Zeipt** [brave/browser-android#655]
It seems like privacy issue..

**Comment by SergeyZhukovsky** [comment]
You could build it with a fake youtube key, but some of functionality won't work.
But you need a key for crashlytics. It gives you one on crashlytics SDK.

**Comment by Zeipt** [comment]
So, it will leak dumps to some untrusted (by default) centralised service on any error? Even if I don't want that? Isn't this "tracking"? As youtube. For example, will it send the same fake youtube key again and again on every embedded youtube's video on any page I visit? It is "tracking", guys, even with fake apikeys..

**Comment by bbondy** [comment]
At first I first misunderstood your report and just understood that there was a problem building.  Thanks for the report.

We'll definitely be exposing options to disable this and we'll weigh the value of the youtube API key.  You'll be able to turn on/off crash reporting but we do want crash reporting because it helps the quality of the product a lot.  I posted #660 for the option to disable crash reporting to do thatt, and we can use this issue to discuss the API key more.

I believe the embeded youtube videos are the thing that tracks though, the API just says that it's a Link Bubble device. All Link Bubble users will be using the same key, so it is not a per user identifier.

We're building a lot of tracking protection into the app and you'll be able to block things and customize the defaults.  We're also investigating using different independent session partitions to preserve privacy and still use 3rd party features on sites.

It will take some time to transition from Link Bubble to Brave, but we're definitely committed to unmatched privacy on Brave.  Thanks for the report, keep them coming!  See http://www.brave.com for more information on Brave.

**Comment by Zeipt** [comment]
ok! Thanx!
